context:
  version: "16.3.3"

package:
  name: turbopack-cli
  version: ${{ version }}

source:
  url: https://github.com/vercel/next.js/archive/v${{ version }}.tar.gz
  sha256: 4a2bcd7ba97c9da71f99481c22ee4ed979d23d29dfc5fdba6c52d2babe6b9719

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - turbopack-cli --help

about:
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  summary: CLI for turbopack
  homepage: https://github.com/vercel/next.js
  repository: https://github.com/vercel/next.js

extra:
  recipe-maintainers:
    - danielnachun
