context:
  version: "16.3.1"

package:
  name: turbopack-cli
  version: ${{ version }}

source:
  url: https://github.com/vercel/next.js/archive/v${{ version }}.tar.gz
  sha256: b14fd7648da2039295796d0ad1aedc5471fddd54659e62c98e2de313ad2de6d1

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - turbopack-cli --help

about:
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  summary: CLI for turbopack
  homepage: https://github.com/vercel/next.js
  repository: https://github.com/vercel/next.js

extra:
  recipe-maintainers:
    - danielnachun
